test docker

diff --git a/bidseq b/bidseq
--- a/bidseq
+++ b/bidseq
@@ -22,41 +22,102 @@ logo="
 \033[1;34m     ╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝        \033[0m
 "
 
+
+
+
+
 printf "$logo\n"
 
 # Set default values
 conf="data.yaml"
-jobs=48
+cores=48
+snake="/opt/pipeline/Snakefile"
 
 # https://stackoverflow.com/a/62616466/5693642
 # Convenience functions.
-usage_error () { echo >&2 "$(basename $0):  $1"; exit 2; }
-assert_argument () { test "$1" != "$EOL" || usage_error "$2 requires an argument"; }
+usage_error() {
+  echo >&2 "$(basename $0):  $1"
+  exit 2
+}
+assert_argument() { test "$1" != "$EOL" || usage_error "$2 requires an argument"; }
 
 # One loop, nothing more.
 if [ "$#" != 0 ]; then
   EOL=$(echo '\01\03\03\07')
   set -- "$@" "$EOL"
   while [ "$1" != "$EOL" ]; do
-    opt="$1"; shift
+    opt="$1"
+    shift
     case "$opt" in
 
-      # Your options go here.
-      -q|--quite) quite='true';;
-      -j|--jobs) assert_argument "$1" "$opt"; jobs="$1"; shift;;
-      -c|--conf) assert_argument "$1" "$opt"; conf="$1"; shift;;
+    # Your options go here.
+    -q | --quite) quite='true' ;;
+    -j | --jobs | --cores)
+      assert_argument "$1" "$opt"
+      cores="$1"
+      shift
+      ;;
+    -c | --conf)
+      assert_argument "$1" "$opt"
+      conf="$1"
+      shift
+      ;;
+    -s | --snake)
+      assert_argument "$1" "$opt"
+      snake="$1"
+      shift
+      ;;
+    -p | --profile)
+      assert_argument "$1" "$opt"
+      profile="$1"
+      shift
+      ;;
 
-      # Arguments processing. You may remove any unneeded line after the 1st.
-      -|''|[!-]*) set -- "$@" "$opt";;                                          # positional argument, rotate to the end
-      --*=*)      set -- "${opt%%=*}" "${opt#*=}" "$@";;                        # convert '--name=arg' to '--name' 'arg'
-      -[!-]?*)    set -- $(echo "${opt#-}" | sed 's/\(.\)/ -\1/g') "$@";;       # convert '-abc' to '-a' '-b' '-c'
-      --)         while [ "$1" != "$EOL" ]; do set -- "$@" "$1"; shift; done;;  # process remaining arguments as positional
-      -*)         usage_error "unknown option: '$opt'";;                        # catch misspelled options
-      *)          usage_error "this should NEVER happen ($opt)";;               # sanity test for previous patterns
+    # Arguments processing. You may remove any unneeded line after the 1st.
+    - | '' | [!-]*) set -- "$@" "$opt" ;;                             # positional argument, rotate to the end
+    --*=*) set -- "${opt%%=*}" "${opt#*=}" "$@" ;;                    # convert '--name=arg' to '--name' 'arg'
+    -[!-]?*) set -- $(echo "${opt#-}" | sed 's/\(.\)/ -\1/g') "$@" ;; # convert '-abc' to '-a' '-b' '-c'
+    --) while [ "$1" != "$EOL" ]; do
+      set -- "$@" "$1"
+      shift
+    done ;;                                             # process remaining arguments as positional
+    -*) usage_error "unknown option: '$opt'" ;;         # catch misspelled options
+    *) usage_error "this should NEVER happen ($opt)" ;; # sanity test for previous patterns
 
     esac
   done
-  shift  # $EOL
+  shift # $EOL
 fi
 
-FLASK_ENV=development snakemake -j ${jobs} -q --rerun-incomplete -s /opt/pipeline/Snakefile --configfiles /opt/pipeline/config.yaml ${conf}
+panoptes --ip 0.0.0.0 --port 5000 2>/dev/null &
+export PANOPTES_PID=$!
+echo "PANOPTES_PID=$PANOPTES_PID"
+trap 'kill -s SIGKILL $PANOPTES_PID' EXIT
+while true; do
+  if curl -s http://127.0.0.1:5000/api/service-info | grep -q running; then
+    echo -e "\033[0;32mPLEASE MONITOR THE PIPELINE AT\033[0m http://127.0.0.1:5000"
+    echo -e "\033[0;32mIf you are running this pipeline on a remote server, \033[0m"
+    echo -e "\033[0;32mreplace the IP adress with server IP, or set ssh proxy on you local machine.\033[0m"
+    LOGFILE="SACSEQ_LOG_$(date +"%F-%H%M%S").txt"
+    echo -e "\033[0;32mREAD DEBUG LOG AT\033[0m ${LOGFILE}"
+    if [[ -n ${profile} ]]; then
+      PROFILE_SETTING="--profile ${profile}"
+    else
+      PROFILE_SETTING=""
+    fi
+    printf "\033[0;33m Analyzing...\033[0m"
+    snakemake --wms-monitor http://127.0.0.1:5000 -p --rerun-incomplete -s ${snake} -j ${cores} --configfiles /opt/pipeline/config.yaml ${conf} ${PROFILE_SETTING} 1>${LOGFILE} 2>${LOGFILE}
+    if [ $? -eq 0 ]; then
+      printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+      printf "\033[0;32m\xE2\x9C\x94\033[0m Successfully finished all jobs."
+    else
+      printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+      printf "\033[0;31m\xE2\x9D\x8C\033[0m Jobs exit with error!"
+    fi
+    rm .panoptes.db
+    kill -s SIGKILL $PANOPTES_PID
+    break
+  fi
+  echo "$(date) waiting for service to start..."
+  sleep 2
+done
