do not run web report by default

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -27,6 +27,9 @@ printf "$logo\n"
 snake="/pipeline/Snakefile"
 conf="data.yaml"
 
+# PORT=$(shuf -i 60000-65000 -n 1)
+PORT=""
+
 POSITIONAL_ARGS=()
 while [[ $# -gt 0 ]]; do
   case $1 in
@@ -40,8 +43,13 @@ while [[ $# -gt 0 ]]; do
     shift
     shift
     ;;
-  -s | --snake)
+  --mysnake)
     snake="$2"
+    shift
+    shift
+    ;;
+  --myport)
+    PORT="$2"
     shift
     shift
     ;;
@@ -74,31 +82,48 @@ else
   cores=${cores_cmd}
 fi
 
-PORT=$(shuf -i 60000-65000 -n 1)
-panoptes --ip 0.0.0.0 --port ${PORT} 1>/dev/null 2>/dev/null &
-export PANOPTES_PID=$!
-# echo "PANOPTES_PID=$PANOPTES_PID"
-trap 'kill -s SIGKILL $PANOPTES_PID' EXIT
-while true; do
-  if curl -s http://127.0.0.1:${PORT}/api/service-info | grep -q running; then
-    echo -e "\033[0;32mPLEASE MONITOR THE PIPELINE AT\033[0m http://127.0.0.1:${PORT}"
-    echo -e "\033[0;32mIf you are running this pipeline on a remote server,\033[0m"
-    echo -e "\033[0;32mreplace the IP adress with server IP, or set ssh proxy on you local machine.\033[0m"
-    LOGFILE="BIDSEQ_LOG_$(date +"%F-%H%M%S").txt"
-    echo -e "\033[0;32mREAD DEBUG LOG AT\033[0m ${LOGFILE}"
-    printf "\033[0;33m Analyzing...\033[0m"
-    snakemake --wms-monitor http://127.0.0.1:${PORT} --rerun-incomplete --jobs ${cores} --snakefile ${snake} --configfiles /pipeline/config.yaml ${conf} $@ 1>${LOGFILE} 2>${LOGFILE}
-    if [ $? -eq 0 ]; then
-      printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
-      printf "\033[0;32m\xE2\x9C\x94\033[0m Successfully finished all jobs.\n"
-    else
-      printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
-      printf "\033[0;31m\xE2\x9D\x8C\033[0m Jobs exit with error!\n"
-    fi
-    # rm .panoptes.db
-    kill -s SIGKILL $PANOPTES_PID
-    break
+if [ -z "${PORT}" ]; then
+
+  LOGFILE="BIDSEQ_LOG_$(date +"%F-%H%M%S").txt"
+  echo -e "\033[0;32mREAD DEBUG LOG AT\033[0m ${LOGFILE}"
+  printf "\033[0;33m Analyzing...\033[0m"
+  snakemake --rerun-incomplete --jobs ${cores} --snakefile ${snake} --configfiles /pipeline/config.yaml ${conf} $@ 1>${LOGFILE} 2>${LOGFILE}
+  if [ $? -eq 0 ]; then
+    printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+    printf "\033[0;32m\xE2\x9C\x94\033[0m Successfully finished all jobs.\n"
+  else
+    printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+    printf "\033[0;31m\xE2\x9D\x8C\033[0m Jobs exit with error!\n"
   fi
-  echo "$(date) waiting for service to start..."
-  sleep 2
-done
+
+else
+
+  panoptes --ip 0.0.0.0 --port ${PORT} 1>/dev/null 2>/dev/null &
+  export PANOPTES_PID=$!
+  # echo "PANOPTES_PID=$PANOPTES_PID"
+  trap 'kill -s SIGKILL $PANOPTES_PID' EXIT
+  while true; do
+    if curl -s http://127.0.0.1:${PORT}/api/service-info | grep -q running; then
+      echo -e "\033[0;32mPLEASE MONITOR THE PIPELINE AT\033[0m http://127.0.0.1:${PORT}"
+      echo -e "\033[0;32mIf you are running this pipeline on a remote server,\033[0m"
+      echo -e "\033[0;32mreplace the IP adress with server IP, or set ssh proxy on you local machine.\033[0m"
+      LOGFILE="BIDSEQ_LOG_$(date +"%F-%H%M%S").txt"
+      echo -e "\033[0;32mREAD DEBUG LOG AT\033[0m ${LOGFILE}"
+      printf "\033[0;33m Analyzing...\033[0m"
+      snakemake --wms-monitor http://127.0.0.1:${PORT} --rerun-incomplete --jobs ${cores} --snakefile ${snake} --configfiles /pipeline/config.yaml ${conf} $@ 1>${LOGFILE} 2>${LOGFILE}
+      if [ $? -eq 0 ]; then
+        printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+        printf "\033[0;32m\xE2\x9C\x94\033[0m Successfully finished all jobs.\n"
+      else
+        printf "\033[0;33m\b\b\b\b\b\b\b\b\b\b\b\b\b\b\033[0m"
+        printf "\033[0;31m\xE2\x9D\x8C\033[0m Jobs exit with error!\n"
+      fi
+      # rm .panoptes.db
+      kill -s SIGKILL $PANOPTES_PID
+      break
+    fi
+    echo "$(date) waiting for service to start..."
+    sleep 2
+  done
+
+fi
